load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "Osc",
    srcs = [
    		"OscError.cpp",
    		"OscContent.cpp",
    		"OscAddress.cpp",
    		"OscArgument.cpp",
    		"OscMessage.cpp",
    		"OscBundle.cpp", 
            "UdpSocket.cpp",
            "OscSender.cpp",
    		],
    hdrs = [
    		"OscCommon.h",
    		"OscError.h",
    		"OscContent.h",
    		"OscAddress.h",
    		"OscArgument.h",
    		"OscMessage.h",
    		"OscBundle.h",
            "Utils.h",
            "UdpSocket.h",
            "OscSender.h",
    		],
    visibility = [
                   "//visibility:public"
                   ],
)
